# Generated by Django 6.0 on 2026-02-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='uesrname',
            new_name='username',
        ),
    ]
