# Generated by Django 6.0 on 2026-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_uesrname_sellerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
