# Generated by Django 6.0 on 2026-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sellerprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
