# Generated by Django 6.0 on 2026-02-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_sellerprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
